# Python imports
from typing import List

# Project imports
from libertas.libertas_server import LibertasServer
from src.utils import EncryptedUpdate, SrchToken


class LibertasPlusServer(LibertasServer):
    """Libertas+ server implementation.

    Libertas+ is an extension to Libertas, as it features a clean-up procedure to mitigate storage blow-up due to
    updates. It uses a wildcard supporting SSE scheme internally. In addition to the security guarantees and
    functionality provided by the underlying scheme, Libertas+ provides Update Pattern Revealing Backward Privacy.
    """

    def search(
            self,
            srch_token: SrchToken,
    ) -> List[EncryptedUpdate]:
        """Searches the index using a search token, resulting in encrypted results.
        Additionally, carries out the clean-up procedure by removing results from the index.

        :param srch_token: The search token generated by the client
        :type srch_token: SrchToken
        :returns: A list of encrypted updates
        :rtype: List[EncryptedUpdate]
        """
        return self.sigma.search_plus(srch_token)
